POST https://organic-waddle-6qgjrpx4jj6c4rpp-3333.app.github.dev/users HTTP/1.1
Content-Type: application/json
Authorization: token xxx

{
  "name": "John Doe",
  "email": "john@example.com"
}
####

PUT  https://organic-waddle-6qgjrpx4jj6c4rpp-3333.app.github.dev/users/1 HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe update",
  "email": "john@example.com"
}

####

DELETE  https://organic-waddle-6qgjrpx4jj6c4rpp-3333.app.github.dev/users/1 HTTP/1.1

